In [1]:
print("1")

1


In [2]:
print("a")

a


burasi Markdown kismi. yorum satiri

Shift + Enter -> kodu run etme

hücrenin dışına çıkıp klavyeden 'b' tuşuna basarsan yeni hücre açar, 'a' tuşu ile seçilen hücrenin üstüne hücre ekler

hücrenin köşesine gelip yukardan kes e bas sonra başka boş bi hücrenin köşesine tıklayıp yukardan yapıştır a bas hücreyi tamamen kes yapıştır yapma

hücrenin köşesine gelip 'x' e bas kes, başka h.nin köşesine gelip 'v' ye bas h.yi yapıştır, c kopyala

h.nin köşesine gel tıkla, aşağılarda başka h.nin köşesine gel, Shift e basılı tut, aradaki h.leri seçer

2 defa 'd' -> hücreyi siler

_italik_ -> 1 er alt tire arasinda

**kalin** -> 2 ser yildiz arasinda

numerical python demek numpy

listede her eleman için ayrı tip bilgisi tutulur, numpy da fixtype bir array in tamamı int, yani daha az maliyetli



# markdown la büyük başlık oluşturmak için h.lerin başına # konur

## alt başlık ##

# neden numpy

1- veri saklamak daha iyi, optimizasyon olarak daha iyi

2- yuksek seviye vektorel operasyonlar yapilabiliyor

## elimizde onlarca index oldugunda indexleri sorgulamayi fancy index ile yapariz

In [5]:
import numpy as np
a=np.array([-1,-2,-3,-4])

In [2]:
a

array([-1, -2, -3, -4])

In [3]:
np.absolute(a[-3])

2

In [8]:
np.log(np.e)

1.0

## sadik turan python kursu numpy alistirma

In [13]:
a = np.array([10,15,30,45,60])

In [16]:
b = np.arange(50,100,5)
b

array([50, 55, 60, 65, 70, 75, 80, 85, 90, 95])

In [20]:
# 0-100 arasinda esit aralikli 5 sayi uretin
c=np.linspace(0,100,5)
c

array([  0.,  25.,  50.,  75., 100.])

In [26]:
# 10-30 arasi rastgele 4 t.sayi uretin---------bak
d=np.random.randint(10,30, size=4)
d

array([16, 11, 15, 16])

## bu alistirmayi bitir

# PANDAS

* Panel Data: kesit veri ve zaman serisi verisinin bir arada old. veri tipi. klasik veri tutma yaklasimlari yerine zaman indexini daha önemseyen bir veri tutma soz konusudur
* numpy gibi fix type degil. kategorik d.ler ile de numeric lerle de bir arada calisilabilir
* Veri manipulasyonu ve veri analizi icin yazilmis acik kaynak kodlu py lib.i
* 2008 de cikti
* pandas temelinde ekonometrik ve finansal calismalar icin dogmustur. panel veri calismalari icin, zaman serisi calismalari icin
* R DataFrame yapisini Py dunyasina tasimis ve DataFrame ler uzerinde hizli ve etkili calisabilme imkani saglamis


# text okuma

In [2]:
import pandas as pd
#sıfırdan txt okuma
tips = pd.read_csv("my_penguins.txt")

In [3]:
tips.head()

species     island  bill_length_mm  bill_depth_mm  flipper_length_mm  \
0  Adelie  Torgersen            39.1           18.7              181.0   
1  Adelie  Torgersen            39.5           17.4              186.0   
2  Adelie  Torgersen            40.3           18.0              195.0   
3  Adelie  Torgersen             NaN            NaN                NaN   
4  Adelie  Torgersen            36.7           19.3              193.0   

   body_mass_g     sex  
0       3750.0    MALE  
1       3800.0  FEMALE  
2       3250.0  FEMALE  
3          NaN     NaN  
4       3450.0  FEMALE

# Veri Bilimi İçin İstatistik
-> örnek teorisi: ana kitlenin alt kümesi. genelde örneklemler üzerinden çılışırız. py da örneklem değerlendirme vs görücez


-> betimsel istatistikler: merkezi eğilim ve dağılım ölçüleri olarak değinmiştik. kovaryans ve korelasyon kavramlarını da görücez


-> güven aralığı hesaplama


-> olasılık dağılımları: elimizdeki rastgele değişkenlerin dağılımlarına göre olasılık hesaplama


-> hipotez testleri: ab testlerini? öğrenicez


-> varyans analizi: 2 den fazla grup üzerinde ortalamaya ilişkin test yapma işlemleri


-> korelasyon analizi: çok değişkenli yöntemlerin girişi

örneklem dağılımı: birden fazla örneklemin dağılımı